version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mycash-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env.mysql
    volumes:
      - mycashdata:/var/lib/mysql
    networks:
      - mycash-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mycash-app
    volumes:
      - .:/var/www/html:delegated
    networks:
      - mycash-network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: mycash-nginx
    volumes:
      - .:/var/www/html:delegated
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - mycash-network
    depends_on:
      - app

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mycash-artisan
    entrypoint: ["php", "/var/www/html/artisan"]
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - mycash-network

  composer:
    image: composer:2.6
    container_name: mycash-composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: ["composer"]

networks:
  mycash-network:

volumes:
  mycashdata:
